[package]
name = "netrustpy3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "netrustpy3"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.20.0"
priority-queue = "2.0.0"
